# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import appointment_pb2 as appointment__pb2


class AppointmentsServiceStub(object):
    """Definicion del servicio
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAppointments = channel.unary_unary(
                '/AppointmentsService/GetAppointments',
                request_serializer=appointment__pb2.GetAppointmentsRequest.SerializeToString,
                response_deserializer=appointment__pb2.GetAppointmentsResponse.FromString,
                )


class AppointmentsServiceServicer(object):
    """Definicion del servicio
    """

    def GetAppointments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointments,
                    request_deserializer=appointment__pb2.GetAppointmentsRequest.FromString,
                    response_serializer=appointment__pb2.GetAppointmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AppointmentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppointmentsService(object):
    """Definicion del servicio
    """

    @staticmethod
    def GetAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AppointmentsService/GetAppointments',
            appointment__pb2.GetAppointmentsRequest.SerializeToString,
            appointment__pb2.GetAppointmentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
