# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appointment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ppointment.proto\"W\n\x0b\x41ppointment\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tdoctor_id\x18\x02 \x01(\t\x12\x14\n\x0cpatient_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"+\n\x16GetAppointmentsRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\"=\n\x17GetAppointmentsResponse\x12\"\n\x0c\x61ppointments\x18\x01 \x03(\x0b\x32\x0c.Appointment2]\n\x13\x41ppointmentsService\x12\x46\n\x0fGetAppointments\x12\x17.GetAppointmentsRequest\x1a\x18.GetAppointmentsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appointment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPOINTMENT']._serialized_start=21
  _globals['_APPOINTMENT']._serialized_end=108
  _globals['_GETAPPOINTMENTSREQUEST']._serialized_start=110
  _globals['_GETAPPOINTMENTSREQUEST']._serialized_end=153
  _globals['_GETAPPOINTMENTSRESPONSE']._serialized_start=155
  _globals['_GETAPPOINTMENTSRESPONSE']._serialized_end=216
  _globals['_APPOINTMENTSSERVICE']._serialized_start=218
  _globals['_APPOINTMENTSSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
