// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: appointment.proto

package confproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppointmentsServiceClient is the client API for AppointmentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppointmentsServiceClient interface {
	GetAppointments(ctx context.Context, in *GetAppointmentsRequest, opts ...grpc.CallOption) (*GetAppointmentsResponse, error)
}

type appointmentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppointmentsServiceClient(cc grpc.ClientConnInterface) AppointmentsServiceClient {
	return &appointmentsServiceClient{cc}
}

func (c *appointmentsServiceClient) GetAppointments(ctx context.Context, in *GetAppointmentsRequest, opts ...grpc.CallOption) (*GetAppointmentsResponse, error) {
	out := new(GetAppointmentsResponse)
	err := c.cc.Invoke(ctx, "/AppointmentsService/GetAppointments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppointmentsServiceServer is the server API for AppointmentsService service.
// All implementations must embed UnimplementedAppointmentsServiceServer
// for forward compatibility
type AppointmentsServiceServer interface {
	GetAppointments(context.Context, *GetAppointmentsRequest) (*GetAppointmentsResponse, error)
	mustEmbedUnimplementedAppointmentsServiceServer()
}

// UnimplementedAppointmentsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAppointmentsServiceServer struct {
}

func (UnimplementedAppointmentsServiceServer) GetAppointments(context.Context, *GetAppointmentsRequest) (*GetAppointmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppointments not implemented")
}
func (UnimplementedAppointmentsServiceServer) mustEmbedUnimplementedAppointmentsServiceServer() {}

// UnsafeAppointmentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppointmentsServiceServer will
// result in compilation errors.
type UnsafeAppointmentsServiceServer interface {
	mustEmbedUnimplementedAppointmentsServiceServer()
}

func RegisterAppointmentsServiceServer(s grpc.ServiceRegistrar, srv AppointmentsServiceServer) {
	s.RegisterService(&AppointmentsService_ServiceDesc, srv)
}

func _AppointmentsService_GetAppointments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmentsServiceServer).GetAppointments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AppointmentsService/GetAppointments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmentsServiceServer).GetAppointments(ctx, req.(*GetAppointmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppointmentsService_ServiceDesc is the grpc.ServiceDesc for AppointmentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppointmentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AppointmentsService",
	HandlerType: (*AppointmentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppointments",
			Handler:    _AppointmentsService_GetAppointments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appointment.proto",
}
