// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: doctor.proto

package confproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definición de los mensajes de la petición y respuesta
type GetDoctorAppointmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId string `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *GetDoctorAppointmentsRequest) Reset() {
	*x = GetDoctorAppointmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDoctorAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAppointmentsRequest) ProtoMessage() {}

func (x *GetDoctorAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAppointmentsRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorAppointmentsRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *GetDoctorAppointmentsRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type GetDoctorAppointmentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appointments []*Appointment `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"` // lista de citas
}

func (x *GetDoctorAppointmentsResponse) Reset() {
	*x = GetDoctorAppointmentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDoctorAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorAppointmentsResponse) ProtoMessage() {}

func (x *GetDoctorAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *GetDoctorAppointmentsResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

var File_doctor_proto protoreflect.FileDescriptor

var file_doctor_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11,
	0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x51,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x30, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0x69, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x2f, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doctor_proto_rawDescOnce sync.Once
	file_doctor_proto_rawDescData = file_doctor_proto_rawDesc
)

func file_doctor_proto_rawDescGZIP() []byte {
	file_doctor_proto_rawDescOnce.Do(func() {
		file_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_doctor_proto_rawDescData)
	})
	return file_doctor_proto_rawDescData
}

var file_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_doctor_proto_goTypes = []interface{}{
	(*GetDoctorAppointmentsRequest)(nil),  // 0: GetDoctorAppointmentsRequest
	(*GetDoctorAppointmentsResponse)(nil), // 1: GetDoctorAppointmentsResponse
	(*Appointment)(nil),                   // 2: Appointment
}
var file_doctor_proto_depIdxs = []int32{
	2, // 0: GetDoctorAppointmentsResponse.appointments:type_name -> Appointment
	0, // 1: DoctorService.GetDoctorAppointments:input_type -> GetDoctorAppointmentsRequest
	1, // 2: DoctorService.GetDoctorAppointments:output_type -> GetDoctorAppointmentsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_doctor_proto_init() }
func file_doctor_proto_init() {
	if File_doctor_proto != nil {
		return
	}
	file_appointment_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_doctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDoctorAppointmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDoctorAppointmentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doctor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doctor_proto_goTypes,
		DependencyIndexes: file_doctor_proto_depIdxs,
		MessageInfos:      file_doctor_proto_msgTypes,
	}.Build()
	File_doctor_proto = out.File
	file_doctor_proto_rawDesc = nil
	file_doctor_proto_goTypes = nil
	file_doctor_proto_depIdxs = nil
}
